INSERT INTO cities (state_id, city) VALUES ((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AP'), 'Arica'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AP'), 'Camarones'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AP'), 'Putre'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AP'), 'General Lagos'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-TA'), 'Iquique'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-TA'), 'Alto Hospicio'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-TA'), 'Pozo Almonte'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-TA'), 'Camiña'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-TA'), 'Colchane'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-TA'), 'Huara'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-TA'), 'Pica'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AN'), 'Antofagasta'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AN'), 'Mejillones'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AN'), 'Sierra Gorda'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AN'), 'Taltal'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AN'), 'Calama'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AN'), 'Ollagüe'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AN'), 'San Pedro de Atacama'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AN'), 'Tocopilla'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AN'), 'María Elena'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AT'), 'Copiapó'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AT'), 'Caldera'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AT'), 'Tierra Amarilla'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AT'), 'Chañaral'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AT'), 'Diego de Almagro'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AT'), 'Vallenar'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AT'), 'Alto del Carmen'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AT'), 'Freirina'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AT'), 'Huasco'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-CO'), 'La Serena'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-CO'), 'Coquimbo'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-CO'), 'Andacollo'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-CO'), 'La Higuera'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-CO'), 'Paiguano'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-CO'), 'Vicuña'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-CO'), 'Illapel'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-CO'), 'Canela'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-CO'), 'Los Vilos'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-CO'), 'Salamanca'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-CO'), 'Ovalle'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-CO'), 'Combarbalá'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-CO'), 'Monte Patria'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-CO'), 'Punitaqui'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-CO'), 'Río Hurtado'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-VS'), 'Valparaíso'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-VS'), 'Casablanca'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-VS'), 'Concón'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-VS'), 'Juan Fernández'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-VS'), 'Puchuncaví'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-VS'), 'Quintero'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-VS'), 'Viña del Mar'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-VS'), 'Isla de Pascua'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-VS'), 'Los Andes'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-VS'), 'Calle Larga'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-VS'), 'Riconada'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-VS'), 'San Esteban'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-VS'), 'La Ligua'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-VS'), 'Cabildo'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-VS'), 'Papudo'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-VS'), 'Petorca'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-VS'), 'Zapallar'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-VS'), 'Quillota'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-VS'), 'Calera'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-VS'), 'Hijuelas'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-VS'), 'La Cruz'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-VS'), 'Nogales'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-VS'), 'San Antonio'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-VS'), 'Algarrobo'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-VS'), 'Cartagena'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-VS'), 'El Quisco'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-VS'), 'El Tabo'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-VS'), 'Santo Domingo'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-VS'), 'San Felipe'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-VS'), 'Catemu'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-VS'), 'Llaillay'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-VS'), 'Panquehue'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-VS'), 'Putaendo'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-VS'), 'Santa María'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-VS'), 'Quilpué'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-VS'), 'Limache'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-VS'), 'Olmué'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-VS'), 'Villa Alemana'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LI'), 'Rancagua'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LI'), 'Codegua'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LI'), 'Coinco'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LI'), 'Coltauco'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LI'), 'Doñihue'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LI'), 'Graneros'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LI'), 'Las Cabras'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LI'), 'Machalí'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LI'), 'Malloa'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LI'), 'Mostazal'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LI'), 'Olivar'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LI'), 'Peumo'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LI'), 'Pichidegua'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LI'), 'Quinta de Tilcoco'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LI'), 'Rengo'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LI'), 'Requínoa'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LI'), 'San Vicente'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LI'), 'Pichilemu'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LI'), 'La Estrella'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LI'), 'Litueche'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LI'), 'Marichihue'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LI'), 'Navidad'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LI'), 'Paredones'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LI'), 'San Fernando'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LI'), 'Chépica'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LI'), 'Chimbarongo'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LI'), 'Lolol'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LI'), 'Nancagua'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LI'), 'Palmilla'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LI'), 'Peralillo'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LI'), 'Placilla'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LI'), 'Pumanque'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LI'), 'Santa Cruz'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-ML'), 'Talca'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-ML'), 'Constitución'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-ML'), 'Curepto'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-ML'), 'Empedrado'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-ML'), 'Maule'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-ML'), 'Pelarco'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-ML'), 'Pencahue'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-ML'), 'Río Claro'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-ML'), 'San Clemente'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-ML'), 'San Rafael'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-ML'), 'Cauquenes'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-ML'), 'Chanco'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-ML'), 'Pelluhue'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-ML'), 'Curicó'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-ML'), 'Hualañé'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-ML'), 'Licantén'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-ML'), 'Molina'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-ML'), 'Rauco'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-ML'), 'Romeral'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-ML'), 'Sagrada Familia'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-ML'), 'Teno'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-ML'), 'Vichuquén'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-ML'), 'Linares'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-ML'), 'Colbún'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-ML'), 'Longaví'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-ML'), 'Parral'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-ML'), 'Retiro'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-ML'), 'San Javier'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-ML'), 'Villa Alegre'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-ML'), 'Yerbas Buenas'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Concepción'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Coronel'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Chiguayante'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Florida'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Hualqui'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Lota'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Penco'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'San Pedro de la Paz'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Santa Juana'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Talcahuano'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Tomé'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Hualpén'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Lebu'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Arauco'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Cañete'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Contulmo'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Curanilahue'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Los Álamos'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Tirúa'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Los Ángeles'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Antuco'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Cabrero'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Laja'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Mulchén'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Nacimiento'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Negrete'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Quilaco'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Quilleco'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'San Rosendo'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Santa Bárbara'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Tucapel'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Yumbel'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Alto Biobío'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Chillán'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Bulnes'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Cobquecura'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Coelemu'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Coihueco'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Chillán Viejo'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'El Carmen'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Ninhue'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Ñiquén'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Pemuco'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Pinto'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Portezuelo'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Quillón'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Quirihue'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Ránquil'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'San Carlos'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'San Fabián'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'San Ignacio'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'San Nicolás'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Treguaco'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-BI'), 'Yungay'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AR'), 'Temuco'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AR'), 'Carahu'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AR'), 'Cunco'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AR'), 'Curarrehue'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AR'), 'Freire'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AR'), 'Galvarin'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AR'), 'Gorbea'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AR'), 'Lautaro'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AR'), 'Loncoche'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AR'), 'Melipeuco'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AR'), 'Nueva Imperial'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AR'), 'Padre las Casa'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AR'), 'Perquenco'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AR'), 'Pitrufquén'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AR'), 'Pucó'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AR'), 'Saavedra'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AR'), 'Teodoro Schmid'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AR'), 'Toltén'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AR'), 'Vilcún'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AR'), 'Villarrica'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AR'), 'Cholchol'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AR'), 'Angol'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AR'), 'Collipulli'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AR'), 'Curacautín'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AR'), 'Ercilla'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AR'), 'Lonquimay'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AR'), 'Los Sauces'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AR'), 'Lumaco'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AR'), 'Purén'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AR'), 'Renaico'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AR'), 'Traiguén'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AR'), 'Victoria'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LR'), 'Valdivia'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LR'), 'Corral'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LR'), 'Lanco'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LR'), 'Los Lagos'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LR'), 'Máfil'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LR'), 'Mariquina'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LR'), 'Paillaco'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LR'), 'Panguipulli'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LR'), 'La Unión'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LR'), 'Futrono'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LR'), 'Lago Ranco'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LR'), 'Río Bueno'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LL'), 'Puerto Montt'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LL'), 'Calbuco'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LL'), 'Cochamó'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LL'), 'Fresia'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LL'), 'Frutillar'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LL'), 'Los Muermos'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LL'), 'Llanquihue'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LL'), 'Maullín'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LL'), 'Puerto Varas'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LL'), 'Castro'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LL'), 'Ancud'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LL'), 'Chonchi'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LL'), 'Curaco de Vélez'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LL'), 'Dalcahue'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LL'), 'Puqueldón'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LL'), 'Queilén'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LL'), 'Quellón'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LL'), 'Quemchi'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LL'), 'Quinchao'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LL'), 'Osorno'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LL'), 'Puerto Octay'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LL'), 'Purranque'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LL'), 'Puyehue'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LL'), 'Río Negro'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LL'), 'San Juan de la Costa'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LL'), 'San Pablo'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LL'), 'Chaitén'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LL'), 'Futaleufú'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LL'), 'Hualaihué'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-LL'), 'Palena'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AI'), 'Coihaique'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AI'), 'Lago Verde'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AI'), 'Aisén'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AI'), 'Cisnes'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AI'), 'Guaitecas'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AI'), 'Cochrane'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AI'), 'O’Higgins'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AI'), 'Tortel'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AI'), 'Chile Chico'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-AI'), 'Río Ibáñez'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-MA'), 'Punta Arenas'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-MA'), 'Laguna Blanca'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-MA'), 'Río Verde'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-MA'), 'San Gregorio'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-MA'), 'Cabo de Hornos (Ex. Navarino)'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-MA'), 'Antártica'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-MA'), 'Porvenir'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-MA'), 'Primavera'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-MA'), 'Timaukel'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-MA'), 'Natales'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-MA'), 'Torres del Paine'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'Santiago'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'Cerrillos'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'Cerro Navia'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'Conchalí'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'El Bosque'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'Estación Central'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'Huechuraba'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'Independencia'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'La Cisterna'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'La Florida'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'La Granja'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'La Pintana'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'La Reina'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'Las Condes'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'Lo Barnechea'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'Lo Espejo'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'Lo Prado'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'Macul'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'Maipú'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'Ñuñoa'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'Pedro Aguirre Cerda'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'Peñalolén'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'Providencia'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'Pudahuel'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'Quilicura'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'Quinta Normal'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'Recoleta'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'Renca'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'San Joaquín'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'San Miguel'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'San Ramón'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'Vitacura'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'Puente Alto'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'Pirque'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'San José de Maipo'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'Colina'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'Lampa'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'Tiltil'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'San Bernardo'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'Buin'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'Calera de Tango'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'Paine'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'Melipilla'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'Alhué'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'Curacaví'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'María Pinto'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'San Pedro'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'Talagante'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'El Monte'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'Isla de Maipo'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'Padre Hurtado'),
((SELECT id FROM states WHERE country_id = 2 AND acronym = 'CL-RM'), 'Peñaflor');