INSERT INTO countries (id, country, acronym) VALUES ('1', 'Argentina', 'ARG'),
('2', 'Chile', 'CHL'),
('3', 'Brasil', 'BRA');

INSERT INTO states (country_id, state, acronym) VALUES ('1', 'Capital Federal', 'CAB'),
('1', 'Buenos Aires', 'BSA'),
('1', 'Catamarca', 'CAT'),
('1', 'Córdoba', 'COR'),
('1', 'Corrientes', 'CRR'),
('1', 'Chaco', 'CHA'),
('1', 'Chubut', 'CHU'),
('1', 'Entre Ríos', 'ENT'),
('1', 'Formosa', 'FOR'),
('1', 'Jujuy', 'JUJ'),
('1', 'La Pampa', 'PAM'),
('1', 'La Rioja', 'RIO'),
('1', 'Mendoza', 'MEN'),
('1', 'Misiones', 'MIS'),
('1', 'Neuquén', 'NEU'),
('1', 'Río Negro', 'RNE'),
('1', 'Salta', 'SAL'),
('1', 'San Juan', 'SJU'),
('1', 'San Luis', 'SLU'),
('1', 'Santa Cruz', 'SCR'),
('1', 'Santa Fe', 'SFE'),
('1', 'Santiago del Estero', 'SDE'),
('1', 'Tierra del Fuego', 'TDF'),
('1', 'Tucumán', 'TUC');

INSERT INTO states (country_id, state, acronym) VALUES ('2', 'Arica y Parinacota', 'CL-AP'),
('2', 'Tarapacá', 'CL-TA'),
('2', 'Antofagasta', 'CL-AN'),
('2', 'Atacama', 'CL-AT'),
('2', 'Coquimbo', 'CL-CO'),
('2', 'Valparaíso', 'CL-VS'),
('2', 'Región del Libertador Gral. Bernardo O\'Higgins', 'CL-LI'),
('2', 'Región del Maule', 'CL-ML'),
('2', 'Región del Biobío', 'CL-BI'),
('2', 'Región de la Araucanía', 'CL-AR'),
('2', 'Región de los Ríos', 'CL-LR'),
('2', 'Región de los Lagos', 'CL-LL'),
('2', 'Región Aisén del Gral. Carlos Ibañez del Campo', 'CL-AI'),
('2', 'Región de Magallanes y de la Antártica Chilena', 'CL-MA'),
('2', 'Región Metropolitana de Santiago', 'CL-RM');

INSERT INTO states (country_id, state, acronym) VALUES ('3', 'Acre', 'AC'),
('3', 'Alagoas', 'AL'),
('3', 'Amazonas', 'AM'),
('3', 'Amapá', 'AP'),
('3', 'Bahia', 'BA'),
('3', 'Ceará', 'CE'),
('3', 'Distrito Federal', 'DF'),
('3', 'Espírito Santo', 'ES'),
('3', 'Goiás', 'GO'),
('3', 'Maranhão', 'MA'),
('3', 'Minas Gerais', 'MG'),
('3', 'Mato Grosso do Sul', 'MS'),
('3', 'Mato Grosso', 'MT'),
('3', 'Pará', 'PA'),
('3', 'Paraíba', 'PB'),
('3', 'Pernambuco', 'PE'),
('3', 'Piauí', 'PI'),
('3', 'Paraná', 'PR'),
('3', 'Rio de Janeiro', 'RJ'),
('3', 'Rio Grande do Norte', 'RN'),
('3', 'Rondônia', 'RO'),
('3', 'Roraima', 'RR'),
('3', 'Rio Grande do Sul', 'RS'),
('3', 'Santa Catarina', 'SC'),
('3', 'Sergipe', 'SE'),
('3', 'São Paulo', 'SP'),
('3', 'Tocantins', 'TO');